GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWlrZSIsImlhdCI6MTc1MTEwNTUwMCwiZXhwIjoxNzUxMTA1NTQ1fQ.Aq4eE_GELp4RVj2GDbwagWrrpufsBaKYJ5wFthqpU98
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWlrZSIsImlhdCI6MTc1MTEwNTQzN30.3eqVshuQNBsJkdMguDgXraRPyACho0c4haAwZmz7iEY"
}
###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWlrZSIsImlhdCI6MTc1MTEwNTQzN30.3eqVshuQNBsJkdMguDgXraRPyACho0c4haAwZmz7iEY"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Mike"
}
